language: cpp

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_HOST
    - secure: "N4bq3OgfnQRMLo0D+sDj8VS6tuvOs+hjCmtIpgbDe+dYqKxR+y7RMrLI05u0atSjvkuclLtoKz1/Nl1wpJOKrdTIoM0g2izDwnxVxZgF86q3LQD3+mtUQUqUKNK6wNJm2j29TdoLkLUpI2w5Rtesitb6XHwq/YI3ETd/AaOzbcvAEtzFnkVrBRBbEcXKwkccQ1ebSQGcYjWZJwcRCiOxfaDZtzEvXmCNmZ00Pozlc65BjqP8wzrZzxwcC4BYiL4K9clNxw5hRK6e7N8V9YIOuqWaF+Q5ublP84KrgeQZlw1v5/j0Y7ZyHOYCOnGB0OMWsfyFxFhCeVHWg1AF0knm7PKyf9VGRTSgKMB01STs7786Ym87mue/bjq6APJpOIeZMB2XimOQtsfszNEl1anLvBiZyv3V6JgaKULTX+IXPJSU6G7JXMQau/7DCdqgEFbu67VqpMZ4YmtossL659wYMMgRD2NWNKyPofUHKS7qOgrWVTcRzLhFesPhqUgsIKCU7Htt+E5v3GcY4mR70xJefFSUyJSYFRbYCfxBaBDnPNKNyWeVc0OTi02v27K4NdmQNp34Q6QJwCqW1LAZseki+kELj7DZ8RpOeEJmL9sQwJASKbqYxXnjsRHzMGtT88GdXlaABymYxnGu6wxdgH27OgcLwAjwf9+C9Ap4xzWe/zE="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build.sh

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
